on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}
  load_test:
    needs: build
    runs-on: ubuntu-latest
    name: Start a load test
    steps:
      - name: Run test in LoadRunner Cloud
        uses: MicroFocus/lrc-gh-action@v1
        id: lrc_run_test
        env:
          LRC_CLIENT_ID: ${{secrets.LRC_CLIENT_ID}}
          LRC_CLIENT_SECRET: ${{secrets.LRC_CLIENT_SECRET}}
        with:
          lrc_server: 'https://stg-srl.saas.microfocus.com'
          lrc_tenant: '809732732'
          lrc_project: '66'
          lrc_test_id: '1873'  
