on:
  workflow_dispatch

jobs:
  run_test:
    uses: MicroFocus/lrc-gh-action/.github/workflows/lrc.yml@v1
    with:
      lrc_server: 'https://stg-srl.saas.microfocus.com'
      lrc_tenant: '809732732'
      lrc_project: '66'
      lrc_test_id: '1873'
    secrets:
      LRC_CLIENT_ID: ${{ secrets.LRC_CLIENT_ID }}
      LRC_CLIENT_SECRET: ${{ secrets.LRC_CLIENT_SECRET }}
  print_run_id:
    runs-on: ubuntu-latest
    needs: run_test
    steps:
      - run: echo "LRC Run ID is ${{ needs.run_test.outputs.lrc_run_id }}"

      
