on:
  workflow_dispatch:

jobs:
  run_test:
    # replace the commit hash with latest
    uses: MicroFocus/lrc-gh-action/.github/workflows/lrc.yml@76349dece5d2f40244c31892dc56a3ac75f2b7dd
    with:
      lrc_server: 'https://srl-qa1.saas.microfocus.com'
      lrc_tenant: '336275311'
      lrc_project: '2'
      lrc_test_id: '2443'
    secrets:
      LRC_CLIENT_ID: ${{ secrets.LRC_CLIENT_ID_QA1 }}
      LRC_CLIENT_SECRET: ${{ secrets.LRC_CLIENT_SECRET_QA1 }}
  print_run_id:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: run_test
    steps:
      - run: echo "LRC Run ID is ${{ needs.run_test.outputs.lrc_run_id }}"
